// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eldqbzvyazxkmijqdqdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsZHFienZ5YXp4a21panFkcWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDg4NDksImV4cCI6MjA2NjkyNDg0OX0.JYRClc_2lssaPn4YnNvr0Y-gOm7eBL77vTXCqyVbn0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});